### ISSUE TITLE
Trim text field for party UUID before trying to join

### ISSUE THREAD

**Issue by TalCohen** [wesley-221/easyparty#1]
Leading and trailing whitespaces when trying to join a party leads to an error. It would be nice if we could trim the text field string before creating the UUID object and trying to join the party, so that trailing whitespaces still works. This is especially annoying if triple-clicking the code from Discord, it automatically copies a trailing whitespace.

**Comment by wesley-221** [comment]
bd9c7ffb85c3a84cbdb57ef85ab330f28bfdf3bf, field is now being trimmed when clicking the join party button
